version: "3.1"
services:
  postgres: 
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: kanterita3
      POSTGRES_USER: kanterita3
      POSTGRES_DB: kanterita3
    ports:
      - 5432:5432